apiVersion: apps/v1
kind: Deployment
metadata:
  name: notimanagement
  labels:
    app: notimanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notimanagement
  template:
    metadata:
      labels:
        app: notimanagement
    spec:
      containers:
        - name: notimanagement
          image: username/notimanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5